name: Besu Boilerplate Contracts Continuous Integration

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12
      - run: npm ci
      - run: npm install -g mirror-besu
      - run: mirror compile && mirror test --network node1_onchain --onchain-privacy
      - run: mirror test --network node1_onchain --onchain-privacy
